title: "c8volt: Camunda 8 Operations CLI"
description: "The tool for Camunda 8 admins and developers to verify outcomes."

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

url: "https://grafvonb.github.io"
baseurl: "/c8volt"
