title: c8volt â€“ Camunda 8 CLI
description: Command Line Interface (CLI) for Camunda 8
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

url: "https://grafvonb.github.io"
baseurl: "/c8volt"

minima:
  skin: auto
